version: '3'
services:
  python:
    # image: trinitronx/python-simplehttpserver

    build:
      context: docker/python
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
